# Generated by Django 5.0.1 on 2025-12-16 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('approve', 'Approbation'), ('reject', 'Rejet')], max_length=20)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'genealogy_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('maiden_name', models.CharField(blank=True, help_text='Nom de jeune fille', max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=200, null=True)),
                ('death_place', models.CharField(blank=True, max_length=200, null=True)),
                ('biography', models.TextField(blank=True, help_text='Histoire de vie, anecdotes, souvenirs', null=True)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('family', 'Famille seulement'), ('private', 'Privé')], default='family', max_length=20)),
                ('is_deceased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_people', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_people', to=settings.AUTH_USER_MODEL)),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'genealogy_person',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership_type', models.CharField(choices=[('marriage', 'Mariage'), ('partnership', 'Union libre'), ('engagement', 'Fiançailles')], default='marriage', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text="Date de mariage ou début de l'union", null=True)),
                ('end_date', models.DateField(blank=True, help_text="Date de divorce ou fin de l'union", null=True)),
                ('location', models.CharField(blank=True, help_text='Lieu de mariage', max_length=200, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposé'), ('confirmed', 'Confirmé'), ('rejected', 'Rejeté')], default='proposed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_person1', to='genealogy.person')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_person2', to='genealogy.person')),
            ],
            options={
                'db_table': 'genealogy_partnership',
            },
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('biological', 'Biologique'), ('adopted', 'Adopté'), ('stepchild', 'Beau-fils/Belle-fille'), ('foster', "Famille d'accueil")], default='biological', max_length=20)),
                ('status', models.CharField(choices=[('proposed', 'Proposé'), ('confirmed', 'Confirmé'), ('rejected', 'Rejeté')], default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='genealogy.person')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_relationships', to='genealogy.person')),
            ],
            options={
                'db_table': 'genealogy_parent_child',
            },
        ),
        migrations.CreateModel(
            name='ModificationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Nom du champ à modifier', max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField()),
                ('justification', models.TextField(help_text='Justification de la modification')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_modifications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_modifications', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_proposals', to='genealogy.person')),
            ],
            options={
                'db_table': 'genealogy_modification_proposal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('birth', 'Naissance'), ('death', 'Décès'), ('marriage', 'Mariage'), ('divorce', 'Divorce'), ('baptism', 'Baptême'), ('graduation', 'Diplôme'), ('other', 'Autre')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('people', models.ManyToManyField(related_name='events', to='genealogy.person')),
            ],
            options={
                'db_table': 'genealogy_family_event',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Acte de naissance'), ('death_certificate', 'Acte de décès'), ('marriage_certificate', 'Acte de mariage'), ('photo', 'Photo'), ('document', 'Document'), ('other', 'Autre')], max_length=30)),
                ('file', models.FileField(upload_to='documents/')),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('people', models.ManyToManyField(blank=True, related_name='documents', to='genealogy.person')),
            ],
            options={
                'db_table': 'genealogy_document',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='genealogy_p_last_na_eef29a_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['birth_date'], name='genealogy_p_birth_d_c5547a_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['created_by'], name='genealogy_p_created_6533de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnership',
            unique_together={('person1', 'person2')},
        ),
        migrations.AlterUniqueTogether(
            name='parentchild',
            unique_together={('parent', 'child')},
        ),
    ]
