# Generated by Django 5.0.1 on 2025-12-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='clan',
            field=models.CharField(blank=True, help_text="Clan d'appartenance", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='tribus',
            field=models.CharField(blank=True, help_text="Tribu d'appartenance", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposé'), ('confirmed', 'Confirmé'), ('rejected', 'Rejeté')], default='confirmed', max_length=20),
        ),
    ]
