# Generated by Django 5.0.1 on 2026-01-02 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_person_clan_person_tribus_alter_partnership_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('person_created', 'Nouvelle personne ajoutée'), ('person_edited', 'Personne modifiée'), ('person_deleted', 'Personne supprimée'), ('child_added', 'Relation parent-enfant ajoutée'), ('modification_proposed', 'Proposition de modification'), ('proposal_approved', 'Proposition approuvée'), ('proposal_rejected', 'Proposition rejetée'), ('user_created', 'Nouvel utilisateur créé'), ('user_deleted', 'Utilisateur supprimé'), ('user_deactivated', 'Utilisateur désactivé'), ('partnership_created', 'Nouveau partenariat'), ('system_alert', 'Alerte système')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normal'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, help_text='URL to navigate when notification is clicked', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification should be automatically deleted', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genealogy.person')),
                ('related_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genealogy.modificationproposal')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'genealogy_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='genealogy_n_recipie_45f80a_idx'), models.Index(fields=['notification_type'], name='genealogy_n_notific_4e3a46_idx'), models.Index(fields=['created_at'], name='genealogy_n_created_622b3c_idx')],
            },
        ),
    ]
