"""
Django settings for kanyamukenge_project project.

Generated by Django 5.0.1
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# SECURITY SETTINGS
# ==============================================================================

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-this-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])

# ==============================================================================
# APPLICATION DEFINITION
# ==============================================================================

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  # Pour les filtres de template (timesince, etc.)
]

LOCAL_APPS = [
    'accounts.apps.AccountsConfig',
    'genealogy.apps.GenealogyConfig',
]

THIRD_PARTY_APPS = [
    # Ajouter ici d'autres apps tierces si nécessaire
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kanyamukenge_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # Pour accéder à MEDIA_URL dans les templates
            ],
        },
    },
]

WSGI_APPLICATION = 'kanyamukenge_project.wsgi.application'

# ==============================================================================
# DATABASE
# ==============================================================================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='kanyamukenge_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# ==============================================================================
# AUTHENTICATION
# ==============================================================================

AUTH_USER_MODEL = 'accounts.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# ==============================================================================
# INTERNATIONALIZATION
# ==============================================================================

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Kigali'
USE_I18N = True
USE_TZ = True

# ==============================================================================
# STATIC FILES (CSS, JavaScript, Images)
# ==============================================================================

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ==============================================================================
# MEDIA FILES (User uploads)
# ==============================================================================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==============================================================================
# DEFAULT PRIMARY KEY FIELD TYPE
# ==============================================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# EMAIL SETTINGS
# ==============================================================================

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@kanyamukenge.family')

# ==============================================================================
# OTP SETTINGS
# ==============================================================================

OTP_EXPIRE_MINUTES = config('OTP_EXPIRE_MINUTES', default=10, cast=int)

# ==============================================================================
# PAGINATION SETTINGS
# ==============================================================================

PAGINATE_BY = 20  # Nombre d'éléments par page par défaut

# ==============================================================================
# GENEALOGY SPECIFIC SETTINGS
# ==============================================================================

# Taille maximale des photos en Mo
MAX_PHOTO_SIZE_MB = 10

# Formats de photos acceptés
ALLOWED_PHOTO_FORMATS = ['JPEG', 'PNG', 'JPG']

# Taille de redimensionnement automatique des photos
PHOTO_RESIZE_SIZE = (800, 800)

# ==============================================================================
# SECURITY SETTINGS FOR PRODUCTION
# ==============================================================================

if not DEBUG:
    # HTTPS Settings
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HSTS Settings
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Other security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Session security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    
    # Session timeout (2 heures d'inactivité)
    SESSION_COOKIE_AGE = 7200
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ==============================================================================
# LOGGING
# ==============================================================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'root': {
        'handlers': ['console'],
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'genealogy': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Créer le dossier logs s'il n'existe pas ET ajouter le handler file seulement si le dossier existe
LOGS_DIR = BASE_DIR / 'logs'
if LOGS_DIR.exists() or not DEBUG:
    # Créer le dossier s'il n'existe pas
    LOGS_DIR.mkdir(exist_ok=True)
    
    # Ajouter le handler file
    LOGGING['handlers']['file'] = {
        'level': 'INFO',
        'class': 'logging.FileHandler',
        'filename': LOGS_DIR / 'django.log',
        'formatter': 'verbose',
    }
    
    # Ajouter le handler file aux loggers
    LOGGING['loggers']['accounts']['handlers'].append('file')
    LOGGING['loggers']['genealogy']['handlers'].append('file')
    
# ==============================================================================
# MESSAGE FRAMEWORK
# ==============================================================================

from django.contrib.messages import constants as messages

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'error',
}

# ==============================================================================
# CACHE SETTINGS (pour la production)
# ==============================================================================

if not DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }

# ==============================================================================
# FILE UPLOAD SETTINGS
# ==============================================================================

# Taille maximale des fichiers uploadés (50MB)
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB

# ==============================================================================
# ADMIN SETTINGS
# ==============================================================================

ADMIN_URL = config('ADMIN_URL', default='admin/')

# ==============================================================================
# DEVELOPMENT SETTINGS
# ==============================================================================

if DEBUG:
    # Django Debug Toolbar (à installer si nécessaire : pip install django-debug-toolbar)
    try:
        import debug_toolbar
        INSTALLED_APPS += ['debug_toolbar']
        MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
        
        INTERNAL_IPS = [
            '127.0.0.1',
            'localhost',
        ]
        
        DEBUG_TOOLBAR_CONFIG = {
            'SHOW_TOOLBAR_CALLBACK': lambda request: False,
        }
    except ImportError:
        pass

# ==============================================================================
# CUSTOM SETTINGS FOR KANYAMUKENGE PROJECT
# ==============================================================================

# Nom du projet affiché dans les templates
PROJECT_NAME = "Famille KANYAMUKENGE"

# Email de contact pour les invitations
CONTACT_EMAIL = config('CONTACT_EMAIL', default='admin@kanyamukenge.family')

# URL de base pour les liens dans les emails
BASE_URL = config('BASE_URL', default='http://127.0.0.1:8000')

# Durée de validité des invitations (en jours)
INVITATION_EXPIRE_DAYS = 7

# Permissions par défaut pour les nouveaux utilisateurs
DEFAULT_USER_PERMISSIONS = {
    'can_add_children': True,
    'can_modify_own_info': True,
    'can_view_private_info': False,
    'can_export_data': False,
}

# Niveaux de visibilité des personnes
PERSON_VISIBILITY_CHOICES = [
    ('public', 'Public'),
    ('family', 'Famille seulement'),
    ('private', 'Privé'),
]

# Types de relations parent-enfant
PARENT_CHILD_RELATIONSHIP_TYPES = [
    ('biological', 'Biologique'),
    ('adopted', 'Adopté'),
    ('stepchild', 'Beau-fils/Belle-fille'),
    ('foster', 'Famille Accueil'),
]

# Types d'unions/partenariats
PARTNERSHIP_TYPES = [
    ('marriage', 'Mariage'),
    ('partnership', 'Union libre'),
    ('engagement', 'Fiançailles'),
]

# Configuration GEDCOM
GEDCOM_EXPORT_CONFIG = {
    'charset': 'UTF-8',
    'version': '5.5.1',
    'source': 'Famille KANYAMUKENGE - Plateforme Généalogique',
}

CSRF_TRUSTED_ORIGINS = [
    'https://806844162ac6.ngrok-free.app',
    'http://127.0.0.1:8000',  # optional for local dev
    'http://localhost:8000',  # optional for local dev
]